name: attendance_app
description: "BLE based attendence tracker"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  go_router: ^13.2.0
  dynamic_color: ^1.6.9
  app_settings: ^5.1.1
  permission_handler: ^11.3.0
  ble_peripheral: ^2.0.0
  flutter_blue_plus: ^1.31.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
