name: CI
on:
  workflow_dispatch:

jobs:
  build_ios_without_signing:
    name: Build Flutter (iOS) Without Signing
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - name: Build Flutter IPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r bookadapt_unsigned.ipa Payload
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios_ipa
          path: build/ios/iphoneos/*.ipa
      - name: Upload ios folder
        uses: actions/upload-artifact@v4
        with:
          name: ios_ipa
          path: ios/
